# -*- coding: utf-8 -*-
# 常用会计分录规则库

import functools
from typing import List, Set, Tuple

STANDARD_RULES = [
    {"credit": ["发出商品"], "debit": ["主营业务成本"]},
    {"credit": ["其他收益"], "debit": ["银行存款"]},
    {"credit": ["合同负债"], "debit": ["银行存款"]},
    {"credit": ["银行存款"], "debit": ["管理费用"]},
    {"credit": ["工程物资"], "debit": ["在建工程"]},
    {"credit": ["银行存款"], "debit": ["营业外收入"]},
    {"credit": ["应收账款"], "debit": ["财务费用"]},
    {"credit": ["实收资本"], "debit": ["无形资产"]},
    {"credit": ["应付职工薪酬"], "debit": ["研发支出"]},
    {"credit": ["累计摊销"], "debit": ["管理费用"]},
    {"credit": ["银行存款"], "debit": ["短期借款"]},
    {"credit": ["投资性房地产"], "debit": ["公允价值变动损益"]},
    {"credit": ["应付职工薪酬"], "debit": ["生产成本"]},
    {"credit": ["油气资产减值准备"], "debit": ["资产减值损失"]},
    {"credit": ["贷款损失准备"], "debit": ["信用减值损失"]},
    {"credit": ["固定资产清理"], "debit": ["银行存款"]},
    {"credit": ["应收账款"], "debit": ["应交税费"]},
    {"credit": ["银行存款"], "debit": ["在建工程"]},
    {"credit": ["累计摊销"], "debit": ["销售费用"]},
    {"credit": ["投资收益"], "debit": ["长期股权投资"]},
    {"credit": ["待处理财产损溢"], "debit": ["营业外支出"]},
    {"credit": ["应付账款"], "debit": ["管理费用"]},
    {"credit": ["应付账款"], "debit": ["营业外收入"]},
    {"credit": ["实收资本"], "debit": ["长期股权投资"]},
    {"credit": ["主营业务收入"], "debit": ["合同负债"]},
    {"credit": ["其他应付款"], "debit": ["应付职工薪酬"]},
    {"credit": ["其他权益工具投资"], "debit": ["投资收益"]},
    {"credit": ["银行存款"], "debit": ["营业外支出"]},
    {"credit": ["应收股利"], "debit": ["银行存款"]},
    {"credit": ["主营业务收入"], "debit": ["应收账款"]},
    {"credit": ["固定资产减值准备"], "debit": ["资产减值损失"]},
    {"credit": ["投资性房地产"], "debit": ["无形资产"]},
    {"credit": ["在建工程减值准备"], "debit": ["资产减值损失"]},
    {"credit": ["库存股"], "debit": ["盈余公积"]},
    {"credit": ["待处理财产损溢"], "debit": ["固定资产"]},
    {"credit": ["周转材料"], "debit": ["其他业务成本"]},
    {"credit": ["固定资产清理"], "debit": ["资产处置损益"]},
    {"credit": ["坏账准备"], "debit": ["资产减值损失"]},
    {"credit": ["银行存款"], "debit": ["固定资产"]},
    {"credit": ["长期股权投资"], "debit": ["应收股利"]},
    {"credit": ["应交税费"], "debit": ["应付职工薪酬"]},
    {"credit": ["固定资产"], "debit": ["投资性房地产"]},
    {"credit": ["持有待售资产减值准备"], "debit": ["资产减值损失"]},
    {"credit": ["银行存款"], "debit": ["应付职工薪酬"]},
    {"credit": ["投资收益"], "debit": ["资本公积"]},
    {"credit": ["应交税费"], "debit": ["税金及附加"]},
    {"credit": ["应付账款"], "debit": ["工程物资"]},
    {"credit": ["商誉减值准备"], "debit": ["资产减值损失"]},
    {"credit": ["其他权益工具投资"], "debit": ["银行存款"]},
    {"credit": ["无形资产"], "debit": ["累计摊销"]},
    {"credit": ["应收账款"], "debit": ["应收票据"]},
    {"credit": ["合同资产减值准备"], "debit": ["资产减值损失"]},
    {"credit": ["银行存款"], "debit": ["长期借款"]},
    {"credit": ["股本"], "debit": ["盈余公积"]},
    {"credit": ["应付账款"], "debit": ["固定资产"]},
    {"credit": ["应付利息"], "debit": ["财务费用"]},
    {"credit": ["其他应收款"], "debit": ["管理费用"]},
    {"credit": ["固定资产"], "debit": ["固定资产减值准备"]},
    {"credit": ["无形资产"], "debit": ["投资性房地产"]},
    {"credit": ["银行存款"], "debit": ["应付债券"]},
    {"credit": ["实收资本"], "debit": ["库存商品"]},
    {"credit": ["其他应收款"], "debit": ["销售费用"]},
    {"credit": ["投资收益"], "debit": ["应收股利"]},
    {"credit": ["银行存款"], "debit": ["交易性金融资产"]},
    {"credit": ["固定资产清理"], "debit": ["营业外收入"]},
    {"credit": ["应收账款"], "debit": ["主营业务收入"]},
    {"credit": ["原材料"], "debit": ["待处理财产损溢"]},
    {"credit": ["资本公积"], "debit": ["无形资产"]},
    {"credit": ["交易性金融资产"], "debit": ["公允价值变动损益"]},
    {"credit": ["累计摊销"], "debit": ["制造费用"]},
    {"credit": ["坏账准备"], "debit": ["信用减值损失"]},
    {"credit": ["投资收益"], "debit": ["应收利息"]},
    {"credit": ["投资性房地产减值准备"], "debit": ["资产减值损失"]},
    {"credit": ["交易性金融资产"], "debit": ["投资收益"]},
    {"credit": ["预付账款"], "debit": ["在途物资"]},
    {"credit": ["银行存款"], "debit": ["销售费用"]},
    {"credit": ["其他综合收益"], "debit": ["其他权益工具投资"]},
    {"credit": ["库存股"], "debit": ["应付职工薪酬"]},
    {"credit": ["银行存款"], "debit": ["其他债权投资"]},
    {"credit": ["财务费用"], "debit": ["银行存款"]},
    {"credit": ["长期待摊费用"], "debit": ["管理费用"]},
    {"credit": ["资本公积"], "debit": ["长期股权投资"]},
    {"credit": ["固定资产清理"], "debit": ["营业外支出"]},
    {"credit": ["投资收益"], "debit": ["银行存款"]},
    {"credit": ["主营业务收入"], "debit": ["银行存款"]},
    {"credit": ["长期股权投资减值准备"], "debit": ["资产减值损失"]},
    {"credit": ["递延所得税负债"], "debit": ["所得税费用"]},
    {"credit": ["实收资本"], "debit": ["银行存款"]},
    {"credit": ["长期股权投资"], "debit": ["持有待售资产"]},
    {"credit": ["其他债权投资"], "debit": ["投资收益"]},
    {"credit": ["应付账款"], "debit": ["销售费用"]},
    {"credit": ["银行存款"], "debit": ["研发支出"]},
    {"credit": ["原材料"], "debit": ["其他业务成本"]},
    {"credit": ["主营业务成本"], "debit": ["库存商品"]},
    {"credit": ["递延所得税资产"], "debit": ["所得税费用"]},
    {"credit": ["投资性房地产"], "debit": ["其他业务成本"]},
    {"credit": ["银行存款"], "debit": ["工程物资"]},
    {"credit": ["银行存款"], "debit": ["应付票据"]},
    {"credit": ["银行存款"], "debit": ["其他货币资金"]},
    {"credit": ["银行存款"], "debit": ["合同履约成本"]},
    {"credit": ["原材料"], "debit": ["在建工程"]},
    {"credit": ["实收资本"], "debit": ["原材料"]},
    {"credit": ["交易性金融资产"], "debit": ["银行存款"]},
    {"credit": ["累计折旧"], "debit": ["其他业务成本"]},
    {"credit": ["其他应收款"], "debit": ["库存现金"]},
    {"credit": ["债权投资"], "debit": ["银行存款"]},
    {"credit": ["预付账款"], "debit": ["原材料"]},
    {"credit": ["短期借款"], "debit": ["银行存款"]},
    {"credit": ["银行存款"], "debit": ["材料采购"]},
    {"credit": ["固定资产"], "debit": ["固定资产清理"]},
    {"credit": ["交易性金融资产减值准备"], "debit": ["资产减值损失"]},
    {"credit": ["主营业务收入"], "debit": ["合同资产"]},
    {"credit": ["其他应付款"], "debit": ["银行存款"]},
    {"credit": ["投资性房地产"], "debit": ["银行存款"]},
    {"credit": ["其他业务收入"], "debit": ["预收账款"]},
    {"credit": ["应收利息"], "debit": ["银行存款"]},
    {"credit": ["银行存款"], "debit": ["应付股利"]},
    {"credit": ["应付职工薪酬"], "debit": ["在建工程"]},
    {"credit": ["其他应收款"], "debit": ["制造费用"]},
    {"credit": ["其他债权投资"], "debit": ["银行存款"]},
    {"credit": ["应交税费"], "debit": ["预收账款"]},
    {"credit": ["库存商品"], "debit": ["待处理财产损溢"]},
    {"credit": ["银行存款"], "debit": ["库存现金"]},
    {"credit": ["应收票据"], "debit": ["银行存款"]},
    {"credit": ["主营业务收入"], "debit": ["预计负债"]},
    {"credit": ["应付账款"], "debit": ["材料采购"]},
    {"credit": ["银行存款"], "debit": ["投资性房地产"]},
    {"credit": ["银行存款"], "debit": ["其他收益"]},
    {"credit": ["长期股权投资"], "debit": ["其他综合收益"]},
    {"credit": ["研发支出"], "debit": ["无形资产"]},
    {"credit": ["待处理财产损溢"], "debit": ["以前年度损益调整"]},
    {"credit": ["应交税费"], "debit": ["以前年度损益调整"]},
    {"credit": ["固定资产"], "debit": ["累计折旧"]},
    {"credit": ["主营业务收入"], "debit": ["合同结算"]},
    {"credit": ["银行存款"], "debit": ["无形资产"]},
    {"credit": ["银行存款"], "debit": ["以前年度损益调整"]},
    {"credit": ["银行存款"], "debit": ["制造费用"]},
    {"credit": ["投资性房地产"], "debit": ["资产处置损益"]},
    {"credit": ["库存股"], "debit": ["资本公积"]},
    {"credit": ["应付账款"], "debit": ["投资性房地产"]},
    {"credit": ["无形资产"], "debit": ["银行存款"]},
    {"credit": ["应付账款"], "debit": ["在途物资"]},
    {"credit": ["银行存款"], "debit": ["长期股权投资"]},
    {"credit": ["银行存款"], "debit": ["应付利息"]},
    {"credit": ["其他业务收入"], "debit": ["应收账款"]},
    {"credit": ["银行存款"], "debit": ["合同负债"]},
    {"credit": ["应付账款"], "debit": ["无形资产"]},
    {"credit": ["待处理财产损溢"], "debit": ["管理费用"]},
    {"credit": ["应交税费"], "debit": ["递延所得税负债"]},
    {"credit": ["资本公积"], "debit": ["银行存款"]},
    {"credit": ["应付账款"], "debit": ["制造费用"]},
    {"credit": ["材料采购"], "debit": ["原材料"]},
    {"credit": ["银行存款"], "debit": ["其他业务收入"]},
    {"credit": ["应交税费"], "debit": ["应收账款"]},
    {"credit": ["营业外收入"], "debit": ["银行存款"]},
    {"credit": ["银行存款"], "debit": ["其他应收款"]},
    {"credit": ["固定资产"], "debit": ["待处理财产损溢"]},
    {"credit": ["在建工程"], "debit": ["固定资产"]},
    {"credit": ["银行存款"], "debit": ["其他权益工具投资"]},
    {"credit": ["生产性生物资产减值准备"], "debit": ["资产减值损失"]},
    {"credit": ["无形资产"], "debit": ["无形资产减值准备"]},
    {"credit": ["累计折旧"], "debit": ["管理费用"]},
    {"credit": ["应收票据"], "debit": ["财务费用"]},
    {"credit": ["应收账款"], "debit": ["其他业务收入"]},
    {"credit": ["主营业务成本"], "debit": ["预计负债"]},
    {"credit": ["无形资产"], "debit": ["资产处置损益"]},
    {"credit": ["主营业务收入"], "debit": ["应收票据"]},
    {"credit": ["累计折旧"], "debit": ["销售费用"]},
    {"credit": ["应付股利"], "debit": ["股本"]},
    {"credit": ["实收资本"], "debit": ["固定资产"]},
    {"credit": ["银行存款"], "debit": ["库存股"]},
    {"credit": ["应付职工薪酬"], "debit": ["管理费用"]},
    {"credit": ["营业外收入"], "debit": ["待处理财产损溢"]},
    {"credit": ["银行存款"], "debit": ["商誉"]},
    {"credit": ["库存商品"], "debit": ["发出商品"]},
    {"credit": ["银行存款"], "debit": ["投资收益"]},
    {"credit": ["其他业务收入"], "debit": ["应交税费"]},
    {"credit": ["应付票据"], "debit": ["应付账款"]},
    {"credit": ["持有待售资产"], "debit": ["资产处置损益"]},
    {"credit": ["待处理财产损溢"], "debit": ["库存商品"]},
    {"credit": ["所得税费用"], "debit": ["递延所得税负债"]},
    {"credit": ["制造费用"], "debit": ["生产成本"]},
    {"credit": ["其他综合收益"], "debit": ["其他债权投资"]},
    {"credit": ["应交税费"], "debit": ["固定资产清理"]},
    {"credit": ["银行存款"], "debit": ["应交税费"]},
    {"credit": ["材料采购"], "debit": ["材料成本差异"]},
    {"credit": ["原材料"], "debit": ["合同履约成本"]},
    {"credit": ["银行存款"], "debit": ["固定资产清理"]},
    {"credit": ["股本"], "debit": ["长期股权投资"]},
    {"credit": ["无形资产"], "debit": ["营业外收入"]},
    {"credit": ["其他应收款"], "debit": ["银行存款"]},
    {"credit": ["应交税费"], "debit": ["递延所得税资产"]},
    {"credit": ["银行存款"], "debit": ["在途物资"]},
    {"credit": ["投资收益"], "debit": ["交易性金融资产"]},
    {"credit": ["固定资产"], "debit": ["营业外支出"]},
    {"credit": ["工程物资减值准备"], "debit": ["资产减值损失"]},
    {"credit": ["其他业务收入"], "debit": ["银行存款"]},
    {"credit": ["投资性房地产"], "debit": ["固定资产"]},
    {"credit": ["应付账款"], "debit": ["应交税费"]},
    {"credit": ["无形资产"], "debit": ["在建工程"]},
    {"credit": ["累计摊销"], "debit": ["其他业务成本"]},
    {"credit": ["应付职工薪酬"], "debit": ["合同履约成本"]},
    {"credit": ["应交税费"], "debit": ["银行存款"]},
    {"credit": ["合同履约成本"], "debit": ["主营业务成本"]},
    {"credit": ["债权投资减值准备"], "debit": ["信用减值损失"]},
    {"credit": ["应交税费"], "debit": ["所得税费用"]},
    {"credit": ["无形资产"], "debit": ["营业外支出"]},
    {"credit": ["其他债权投资减值准备"], "debit": ["信用减值损失"]},
    {"credit": ["应交税费"], "debit": ["其他应付款"]},
    {"credit": ["银行存款"], "debit": ["预付账款"]},
    {"credit": ["银行存款"], "debit": ["其他应付款"]},
    {"credit": ["库存现金"], "debit": ["银行存款"]},
    {"credit": ["投资收益"], "debit": ["其他综合收益"]},
    {"credit": ["库存股"], "debit": ["股本"]},
    {"credit": ["存货跌价准备"], "debit": ["资产减值损失"]},
    {"credit": ["其他应收款"], "debit": ["坏账准备"]},
    {"credit": ["长期股权投资"], "debit": ["投资收益"]},
    {"credit": ["应交税费"], "debit": ["应收票据"]},
    {"credit": ["银行存款"], "debit": ["长期待摊费用"]},
    {"credit": ["应收账款"], "debit": ["银行存款"]},
    {"credit": ["原材料"], "debit": ["制造费用"]},
    {"credit": ["待处理财产损溢"], "debit": ["原材料"]},
    {"credit": ["债权投资"], "debit": ["投资收益"]},
    {"credit": ["股本"], "debit": ["资本公积"]},
    {"credit": ["库存商品"], "debit": ["主营业务成本"]},
    {"credit": ["累计折旧"], "debit": ["制造费用"]},
    {"credit": ["固定资产"], "debit": ["持有待售资产"]},
    {"credit": ["所得税费用"], "debit": ["递延所得税资产"]},
    {"credit": ["银行存款"], "debit": ["原材料"]},
    {"credit": ["生产成本"], "debit": ["库存商品"]},
    {"credit": ["以前年度损益调整"], "debit": ["银行存款"]},
    {"credit": ["在途物资"], "debit": ["原材料"]},
    {"credit": ["资产减值损失"], "debit": ["存货跌价准备"]},
    {"credit": ["递延收益"], "debit": ["其他收益"]},
    {"credit": ["资本公积"], "debit": ["固定资产"]},
    {"credit": ["发出商品"], "debit": ["应收账款"]},
    {"credit": ["应付职工薪酬"], "debit": ["制造费用"]},
    {"credit": ["合同结算"], "debit": ["应收账款"]},
    {"credit": ["无形资产"], "debit": ["持有待售资产"]},
    {"credit": ["无形资产减值准备"], "debit": ["资产减值损失"]},
    {"credit": ["应付账款"], "debit": ["原材料"]},
    {"credit": ["债权投资减值准备"], "debit": ["资产减值损失"]},
    {"credit": ["长期借款"], "debit": ["银行存款"]},
    {"credit": ["银行存款"], "debit": ["递延收益"]},
    {"credit": ["预付账款"], "debit": ["材料采购"]},
    {"credit": ["应收账款"], "debit": ["坏账准备"]},
    {"credit": ["银行存款"], "debit": ["财务费用"]},
    {"credit": ["长期股权投资"], "debit": ["银行存款"]},
    {"credit": ["原材料"], "debit": ["研发支出"]},
    {"credit": ["银行存款"], "debit": ["预计负债"]},
    {"credit": ["其他综合收益"], "debit": ["长期股权投资"]},
    {"credit": ["应付职工薪酬"], "debit": ["销售费用"]},
    {"credit": ["递延收益"], "debit": ["银行存款"]},
    {"credit": ["原材料"], "debit": ["生产成本"]},
    {"credit": ["银行存款"], "debit": ["应付账款"]},
    {"credit": ["材料成本差异"], "debit": ["材料采购"]},
    {"credit": ["主营业务收入"], "debit": ["预收账款"]},
    {"credit": ["研发支出"], "debit": ["管理费用"]},
    {"credit": ["银行存款"], "debit": ["债权投资"]},
]

# 预编译关键词列表
UNIQUE_DEBIT_KWS: List[str] = list(set(
    debit_kw for rule in STANDARD_RULES for debit_kw in rule["debit"]
))
UNIQUE_CREDIT_KWS: List[str] = list(set(
    credit_kw for rule in STANDARD_RULES for credit_kw in rule["credit"]
))
RULE_PAIRS: Set[Tuple[str, str]] = set(
    (debit_kw, credit_kw)
    for rule in STANDARD_RULES
    for debit_kw in rule["debit"]
    for credit_kw in rule["credit"]
)

@functools.lru_cache(maxsize=None)
def check_rule_match(debit_subj: str, credit_subj: str) -> bool:
    """
    检查给定的借方科目和贷方科目是否匹配任意一条规则。
    使用缓存和预编译集合优化性能。
    """
    debit_subj = "" if debit_subj is None else str(debit_subj)
    credit_subj = "" if credit_subj is None else str(credit_subj)

    matched_dkws = [kw for kw in UNIQUE_DEBIT_KWS if kw in debit_subj]
    if not matched_dkws:
        return False

    matched_ckws = [kw for kw in UNIQUE_CREDIT_KWS if kw in credit_subj]
    if not matched_ckws:
        return False

    for d_kw in matched_dkws:
        for c_kw in matched_ckws:
            if (d_kw, c_kw) in RULE_PAIRS:
                return True

    return False
